### ISSUE TITLE
Install/compilation instructions are missing

### ISSUE THREAD

**Issue by roveri-marco** [Smart-Contract-Modelling-uOttawa/Symboleo-Model-Checker-Test-Generator#1]
It would be good to include some instructions about the requirements, and how to compile and run.

Moreover, I noticed that there is object code resulting from compilation. This is typically a bad choice 
since it will result in modified files any time one recompiles the code in his computer to be sure
it will be compatible with the environment installed in the computer.

**Comment by parvizi** [comment]
It is done. Many thanks.
